baseURL = 'https://derphilipp.github.io/podcast_redhuhn/'
#baseURL = 'http://redhuhn.einlzweip.de/'
languageCode = 'de-de'
title = 'Redhuhn'

canonifyURLs = true

theme = "castanet"
googleAnalytics = ""
paginate = "9"
buildFuture = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


[permalinks]
	page = "/:filename/"
	  about = "/:filename/"
	  episode = "/:filename/"

#[[Menu.Main]]
#    name = "About"
#    identifier = "about"
#    url = "/about"

#[[Menu.Main]]
#    name = "Contact"
#    identifier = "contact"
#    url = "/contact"

[[Menu.Main]]
    name = "Podcast"
    identifier = "resources"
    url = "#!"


[params]
mainSections = ["episode"]
#episode_number_style  = "brackets"
#episode_number_prefix = "CWC"
site_theme = "blue"
# site_layout = "grid"
site_layout = "row"
show_next_upcoming = "false"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
#01_es_war_einmal.mp3
# https://ia801504.us.archive.org/17/items/redhuhn/02_die_axt_im_haus_erspart_den_zimmermann.mp3
about_logo = "https://archive.org/download/redhuhn/redhuhn.png"
copyright_notice = "Copyright 2021 [Philipp Weißmann](https://www.philipp-weissmann.de)"
itunes_subscribe = "https://podcasts.apple.com/us/podcast/redhuhn/id1470871979"
# itunes_subscribe = "https://podcasts.apple.com/us/podcast/arrested-devops/id773888088?ign-mpt=uo%3D4&mt=2"
# android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
# spotify_subscribe = "https://open.spotify.com/show/..."
spotify_subscribe = "https://open.spotify.com/show/3rgCuBZ0bcSnxjartXjT3T?si=Qp6gcxRDQzSM62ByYRKEtQ"
# google_play_subscribe = "https://podcasts.google.com/feed/aHR0cHM6Ly93d3cuYXJyZXN0ZWRkZXZvcHMuY29tL2VwaXNvZGUvaW5kZXgueG1s"
# stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
# soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
# pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
# mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
# rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Geflügelte Worte und Redewendungen vorgestellt und kurz erklärt"
media_prefix = "https://ia601504.us.archive.org/17/items/redhuhn/"
#media_prefix = "https://media.blubrry.com/arresteddevops/content.blubrry.com/arresteddevops/"
#media_prefix = "https://media.blubrry.com/arresteddevops/content.blubrry.com/arresteddevops/"
disqusShortname = ""

  [params.feed]
    copyright = "Copyright 2021 Philipp Weißmann" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "Geflügelte Worte und Redewendungen" #no markdown or HTML
    itunes_author = "Philipp Weißmann" #no markdown or HTML
    itunes_summary = "Geflügelte Worte und Redewendungen vorgestellt und kurz erklärt" # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Philipp Weißmann"
    itunes_owner_email = "mail@philipp-weissmann.de" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "https://archive.org/download/redhuhn/redhuhn.png" #fqdn to the image art for your podcast
    itunes_top_category = "Education"
    itunes_first_sub_category = "Language Learning"
    # itunes_second_sub_category = "Tech News"
    language = "de-de"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

  [params.podlove] # https://subscribe-button.podlove.org
    subscribe_title = ""              # fallback: site title from above
    subscribe_subtitle = ""           # fallback: ""
    subscribe_description = ""        # fallback: ""
    subscribe_cover = "https://archive.org/download/redhuhn/redhuhn.png"  # fallback: ""
    subscribe_color = "#585e6c"       # fallback: ""
    subscribe_size = "medium"         # options: small, medium, big
    subscribe_format = "rectangle"    # options: rectangle, square, cover
    subscribe_style = "filled"        # options: filled, outline, frameless
    subscribe_language = "de"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
    subscribe_feed_type = "audio"     # options: audio, video
    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
    github = "derphilipp"
    # gitlab = "mattstratton"
    # facebook = "Arresteddevops"
    # facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "derphilipp"
    # twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    # googleplus = "ArrestedDevOps"
    # pinterest = "nozzleio"
    # instagram = "nozzleio"
    # youtube = "arresteddevops"
    # linkedin = "mattstratton"
    # twitch = "mattstratton"

  [params.authors]
    [params.authors.Matt]
      name	= "Philipp Weißmann"
      # thumbnail = "img/host/matt.png"
      # bio = "Matt Stratton is a solutions architect at Chef, where he demonstrates how Chef’s automation platform provides speed and flexibility to clients’ infrastructure. He is devoted to concepts like Continuous Delivery and Infrastructure as Code, and his license plate actually says “DevOps”. He lives in Chicago and has an unhealthy obsession with Doctor Who, Firefly, and Game of Thrones. And whiskey."
      [params.authors.Matt.social]
        github = "derphilipp"
        # facebook = "matt.stratton"
        twitter = "derphilipp"
        # linkedin = "mattstratton"
        # homepage = "https://www.mattstratton.io"
        # pinterest = "mattstratton"
        # instagram = "instagram"
        # youtube = "mattstratton"
        # twitch = "mattstratton"

    # [params.links]
    #   [params.links.ado]
    #     name = "Arrested DevOps"
    #     url = "https://www.arresteddevops.com"
    #   [params.links.ffs]
    #     name = "Food Fight Show"
    #     url = "https://foodfightshow.org"
    #   [params.links.sdt]
    #     name = "Software Defined Talk"
    #     url = "https://cote.io/podcasts/sdt/"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

# [module]
# [[module.imports]]
#   path = 'github.com/mattstratton/castanet'
#   target = 'themes/castanet'
